<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>12.0</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Update="Internals\ValueTupleStrategy.g.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>ValueTupleStrategy.tt</DependentUpon>
        </Compile>
        <None Update="Internals\ValueTupleStrategy.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>ValueTupleStrategy.g.cs</LastGenOutput>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    </ItemGroup>

</Project>
